

// Please give me 5 problems to assign students utilizing the following concepts:
// 1. Loops
// 2. Conditionals
import java.util.Scanner;

public class assignment_3 {
    
    /**
     * Problem 1: Write a program that prints the numbers from 1 to 100. 
     * But for multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". 
     * For numbers which are multiples of both three and five print "FizzBuzz".
     */
     public static void fizbuzz_generator() {
        System.out.println("-------PART 1 OF PROGRAM ----------");
        for(int i=0; i<=100; i++) {

            if (i % 3 == 0) {
                System.out.println("Fizz");

            } else if (i % 5 == 0) {
                System.out.println("Buzz");


            } else {
                System.out.println(i);


            }

        }

     }
    
    /**
     * Problem 2: Write a program that prints the Fibonacci sequence from 0 to 50. 
     * The Fibonacci sequence is a series of numbers where a number is the sum of the two numbers before it. 
     * For example, 0, 1, 1, 2, 3, 5, 8, etc.
    */
    public static void fibonacci_sequence() {
        
        System.out.println("-------PART 2 OF PROGRAM ----------");

        /*the following 9 lines are AI generated by ChatGPT-4-turbo. */
            int n = 50; // Number of terms
            int a = 0, b = 1;
        
            for (int i = 0; i < n; i++) {
                System.out.print(a + " "); // Print current Fibonacci number
                int next = a + b; // Compute next number
                a = b;
                b = next;
            }
        /*END of AI code */
    }

    /**
     * 
     * Problem 3: Write a program that gets the maximum value from  a list of three entered integers
     * @int a - first integer
     * @int b - second integer
     * @int c - third integer
     */
    
    public static int max_value() {
        Scanner scanner = new Scanner(System.in);
        System.out.println("\n-------PART 3 OF PROGRAM ----------");
        // Please replace this with the max integer
        System.out.println("-------Enter 3 intergers of WHOLE numbers.------ \n------ Press ENTER key in between Integers ----------");
        int a = scanner.nextInt();
        
        /* to prevent error, could put in conditonal loop preventing program crash */

        int b = scanner.nextInt();

        int c = scanner.nextInt();

        System.out.println("------- Integers Captured------ \n ------Finishing Program----------");

        int maxINT = a+b+c;

        return maxINT;
    }
    
    public static void main(String[] args) {

        fizbuzz_generator();

        fibonacci_sequence();

        System.out.println("The max value is: " + max_value());

        
    }
    
}
